#!/usr/bin/env sh
set -eu

case "$0" in
  */*) _with_dev_env_entry_dir=${0%/*} ;;
  *) _with_dev_env_entry_dir=. ;;
esac
[ -n "$_with_dev_env_entry_dir" ] || _with_dev_env_entry_dir=/
_with_dev_env_core=$_with_dev_env_entry_dir/_with-dev-env-core.sh
if [ ! -r "$_with_dev_env_core" ]; then
  echo "Missing with-dev-env core: $_with_dev_env_core" >&2
  exit 1
fi
# shellcheck disable=SC1090
. "$_with_dev_env_core"
unset _with_dev_env_entry_dir _with_dev_env_core

_with_dev_env_run 1 "" "$@"
